title: Teresina Hacker Clube
description: O primeiro hackerspace do Piauí, Brasil.
remote_theme: just-the-docs/just-the-docs
url: https://teresinahacker.club
color_scheme: dark
logo: /assets/images/logo.png
favicon_ico: /assets/images/thc_logo.png
